name: Download File

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install download tool
      run: dotnet tool install -g dotnetCampus.FileDownloader.Tool
    - name: Install send mail tool
      run: dotnet tool install -g dotnetCampus.SendEmailTask

    - name: Download File
      run: DownloadFile -u http://d3.jnqcjy.ltd:806/1408/DiskGenius_x86_bkill.com.zip -o file.zip
    - name: Send mail
      uses: dawidd6/action-send-mail@v3
      with :
       server_address :  smtp.qq.com
       server_port : 465 
       username : ${{secrets.LOGINMAILUSER}} 
       password : ${{secrets.LOGINMAILPWD}} 
       subject : Github Actions job result 
       to : 470138890@qq.com
       from : Luke Skywalker
       body : 完成
       attachments: file.zip
   
